name: HaveFunPlayWell
favicon: null
layout_spectrum: 0.15142405638471246
typography_spectrum: 0.8659706574399024
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.8534971345216036
  lightness: 0.9748139122966677
  saturation: 0.8997876821085811
  rhythmicContrast: 0.9567407127469778
purpose: []
