title: 'Have Fun, Play Well - Wells Worswick music performance studio'
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.8997876821085811
  brandStrength: 0.8534971345216036
  rhythmicContrast: 0.9567407127469778
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  lightness: 0.9748139122966677
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: HaveFunPlayWell
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.8659706574399024
layout_spectrum: 0.4780776
